# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20c7f604c47a285668d403d09c14da36472a35f6c814db97d91bde969b43a266e545a829765aa58343068485b03cacd5a19d5d060cedd63d93ef4a07c16ae0eb

test:
  secret_key_base: 75e7e78c80f216c26bc7ba8624ce65cdb48ce516b61dfcc63473a9adef91199ee5b6535e8a10e0d350e14ae1d8f0962498d193f94c51fc2de187d71e8697b0fc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
